name: 'Build Java Maven Action'
#
description: Build a Java/Maven repo

inputs:
  java_version:
    description: The Java version to use
    required: true
  java_distribution:
    description: The Java distribution to use
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ inputs.java_version }}
        distribution: ${{ inputs.java_distribution }}
    - name: Build with Maven
      run: mvn --batch-mode clean package -DskipTests
      shell: bash
    - name: Bump version and push tag
      id: bumpTag2
      uses: anothrNick/github-tag-action@1.36.0
      env:
        # TODO Figure-out how to pass this in
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ github.token }}
        WITH_V: true
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: '**/target/*.jar'
        tag_name: ${{ steps.bumpTag2.outputs.new_tag }}
        
